# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cashctl < Formula
  desc "A wallet CLI for NIP-CASH cash tokens and NIP-CW circle wallets."
  homepage "https://github.com/ohstr/cashctl"
  version "0.0.1"
  license "Unlicense"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ohstr/cashctl/releases/download/v0.0.1/cashctl_darwin_amd64.tar.gz"
      sha256 "2de080df19b2420632eac94001c6c05cc8690e015a6213c67621231b3b04f903"

      define_method(:install) do
        bin.install "cashctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ohstr/cashctl/releases/download/v0.0.1/cashctl_darwin_arm64.tar.gz"
      sha256 "f777cdfe4193d5b0bc3666efb178eea201a8d389ae92fa5cf9ba364f8d3f64ac"

      define_method(:install) do
        bin.install "cashctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohstr/cashctl/releases/download/v0.0.1/cashctl_linux_amd64.tar.gz"
      sha256 "651beb4f10a678b508f5c6547c8d785654ca2bae8397cc35e6f761ee507ca2a7"
      define_method(:install) do
        bin.install "cashctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohstr/cashctl/releases/download/v0.0.1/cashctl_linux_arm64.tar.gz"
      sha256 "dc95415773256590c532b754357961ca9ce98d93713653e9e72fda82501e8d3b"
      define_method(:install) do
        bin.install "cashctl"
      end
    end
  end

  test do
    system "#{bin}/cashctl", "version"
  end
end
