# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ncli < Formula
  desc "A single binary for running and operating Nostr relays: serve, stream, sync, inspect, search, export, and mine events."
  homepage "https://github.com/ohstr/ncli"
  version "0.4.2"
  license "Unlicense"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ohstr/ncli/releases/download/v0.4.2/ncli_darwin_amd64.tar.gz"
      sha256 "701e8dd7588f4564b826676cc80ac1a7baa908c96cbcc8c808c0d75f3ac5151a"

      define_method(:install) do
        bin.install "ncli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ohstr/ncli/releases/download/v0.4.2/ncli_darwin_arm64.tar.gz"
      sha256 "95d615ad69f74ccbdb3e2c0406ea152bdf4f016e8419256b8645517bd202a598"

      define_method(:install) do
        bin.install "ncli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohstr/ncli/releases/download/v0.4.2/ncli_linux_amd64.tar.gz"
      sha256 "87149907ef4787dc696e87133a863e5e75ff1f954c985e157917caeed118763b"
      define_method(:install) do
        bin.install "ncli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohstr/ncli/releases/download/v0.4.2/ncli_linux_arm64.tar.gz"
      sha256 "ea29f2a7d19e134319eb8305fdc2e400eb8ee22cd7d0f62bc97e6268b6149d67"
      define_method(:install) do
        bin.install "ncli"
      end
    end
  end

  test do
    system "#{bin}/ncli", "version"
  end
end
